version: "2"
services:
  web:
    image: yelpcamp-docker
    build: .
    ports:
      - "4444:4444"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"