version: "2"
services:
  web:
    image: yelpcamp-docker:${TAG:-latest}
    build: .
    ports:
      - "8080:80"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"